name: Auto Commit Journal

on:
  schedule:
    - cron: "0 21 * * *"  # chaque jour à 21h UTC
  workflow_dispatch:      # exécutable manuellement depuis GitHub

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        run: python commit_journal.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add journal.csv
          git commit -m "📘 Mise à jour automatique du journal du $(date +'%Y-%m-%d')" || echo "Aucun changement"
          git push
